name: flutter_ckb_localization
description: Flutter Central Kurdish Branch aka Sorani Localization Support
version: 0.0.7
homepage: https://github.com/mustafa96m/flutter_ckb_localization

environment:
  sdk: '>=2.18.2 <3.1.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.1.1
