library flutter_ckb_localization;

export 'package:flutter_ckb_localization/ckb_cupertino_localization_delegate.dart';
export 'package:flutter_ckb_localization/ckb_material_localization_delegate.dart';
export 'package:flutter_ckb_localization/ckb_widget_localization_delegate.dart';
export 'package:flutter_ckb_localization/ku_cupertino_localization_delegate.dart';
export 'package:flutter_ckb_localization/ku_material_localization_delegate.dart';
export 'package:flutter_ckb_localization/ku_widget_localization_delegate.dart';
